"""Restore FK/date indexes used by analytical JOINs and filters.

A prior autogenerated migration dropped several foreign-key indexes
(lab_results.encounter_id, medications.encounter_id, readmissions.*_encounter_id),
and a number of frequently-joined/filtered columns were never indexed. Their
absence forces sequential scans on the multi-table clinical queries the copilot
generates. This migration (re)creates them idempotently.

Revision ID: a1b2c3d4e5f6
Revises: 5222b9dda08f
Create Date: 2026-06-21
"""
from typing import Sequence, Union

from alembic import op

revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "5222b9dda08f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (index_name, table, column)
_INDEXES = [
    ("ix_encounters_department_id", "encounters", "department_id"),
    ("ix_encounters_provider_id", "encounters", "provider_id"),
    ("ix_encounters_discharge_date", "encounters", "discharge_date"),
    ("ix_diagnoses_encounter_id", "diagnoses", "encounter_id"),
    ("ix_procedures_encounter_id", "procedures", "encounter_id"),
    ("ix_procedures_patient_id", "procedures", "patient_id"),
    ("ix_medications_encounter_id", "medications", "encounter_id"),
    ("ix_medications_prescriber_id", "medications", "prescriber_id"),
    ("ix_lab_results_encounter_id", "lab_results", "encounter_id"),
    ("ix_lab_results_result_date", "lab_results", "result_date"),
    ("ix_vital_signs_encounter_id", "vital_signs", "encounter_id"),
    ("ix_vital_signs_patient_id", "vital_signs", "patient_id"),
    ("ix_claims_encounter_id", "claims", "encounter_id"),
    ("ix_claims_patient_id", "claims", "patient_id"),
    ("ix_readmissions_index_encounter_id", "readmissions", "index_encounter_id"),
    ("ix_readmissions_readmit_encounter_id", "readmissions", "readmit_encounter_id"),
]


def upgrade() -> None:
    for name, table, column in _INDEXES:
        op.execute(f'CREATE INDEX IF NOT EXISTS "{name}" ON "{table}" ("{column}")')


def downgrade() -> None:
    for name, _table, _column in _INDEXES:
        op.execute(f'DROP INDEX IF EXISTS "{name}"')
